import type { Metadata } from 'next'
import { Manrope, Cormorant_Infant } from 'next/font/google'
import './globals.css'

const manrope = Manrope({ 
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-manrope',
});

const cormorantInfant = Cormorant_Infant({ 
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-cormorant-infant',
});

export const metadata: Metadata = {
  title: 'Homely - A Real Estate Framer Template',
  description: 'Generated by create next app',
}

// Root layout - provides HTML/body structure for pages outside [locale] (like not-found)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${cormorantInfant.variable} ${manrope.className} bg-white dark:bg-black antialiased`}>
        {children}
      </body>
    </html>
  )
}

