import type { Metadata } from 'next'
import { Manrope, Cormorant_Infant } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import '../globals.css'
import { ThemeProvider } from 'next-themes'
import NextTopLoader from 'nextjs-toploader';
import Header from '../components/layout/header';
import Footer from '../components/layout/footer';
import SessionProviderComp from '../../providers/SessionProvider';
import ScrollToTop from '../components/scroll-to-top';

const manrope = Manrope({ 
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-manrope',
});

const cormorantInfant = Cormorant_Infant({ 
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-cormorant-infant',
});

export const metadata: Metadata = {
  title: 'Homely - A Real Estate Framer Template',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params,
  session,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
  session?: any;
}) {
  const { locale } = await params;
  
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${manrope.variable} ${cormorantInfant.variable} ${manrope.className} bg-white dark:bg-black antialiased`}>
        <NextTopLoader color="#3435AA" />
        <NextIntlClientProvider messages={messages}>
          <SessionProviderComp session={session}>
            <ThemeProvider
              attribute='class'
              enableSystem={true}
              defaultTheme='light'>
              <Header />
              {children}
              <Footer />
              <ScrollToTop />
            </ThemeProvider>
          </SessionProviderComp>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}

